### ISSUE TITLE
[Feature Request] Allow Langchain::Loader to accept a IO object / File Handle / a String

### ISSUE THREAD

**Issue by ProGM** [patterns-ai-core/langchainrb#127]
It would be super-useful to accept an IO Stream or a string directly.

It's particularly useful when you're working with files on cloud storages like Google Drive or S3.

Example:
```ruby
drive = Google::Apis::DriveV3::DriveService.new
raw_content = drive.get_file(my_file_id, download_dest: StringIO.new).string
text = Langchain::Loader.load(raw_content)
```

Without this, I have to do something like:
```ruby
drive = Google::Apis::DriveV3::DriveService.new
temp_file = TempFile.new(my_file_id)
raw_content = drive.get_file(my_file_id, download_dest: temp_file.path)
text = Langchain::Loader.load(temp_file.path)
FileUtils.rm(temp_file.path)
```

**Comment by ProGM** [comment]
@alchaplinsky Because the raw_content could be in any possible (binary) format, like PDF, docx, etc...

For instance I'd like to do:
```ruby
drive = Google::Apis::DriveV3::DriveService.new
# Load all files on google drive
response = drive.list_files(page_size: 1000)

# Load content from any file
response.files.each do |file|
  raw_content = drive.get_file(my_file_id, download_dest: StringIO.new).string
  text = Langchain::Loader.load(raw_content)
  ...
rescue Langchain::Loader::UnknownFormatError => e
  puts "File skipped: #{e.message}"
end
```

**Comment by andreibondarev** [comment]
@ProGM Isn't there a way to be able to tell what the file type is ahead of time with this method?
```ruby
response.files.each do |file|
   file.file_extension
```
Method: [#file_extension](https://googleapis.dev/ruby/google-api-client/latest/Google/Apis/DriveV3/File.html#file_extension-instance_method)

**Comment by ProGM** [comment]
Uhm... Well, yes. As I said before, it's not that you can't work around (for instance, if you use a Tempfile, it just works), it's just pretty common in libraries that work with files to accept a File handle / IO instead of the string path.

In fact, internally [DocX](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/processors/docx.rb#L19), [pdf](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/processors/pdf.rb#L19) and [CSV](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/processors/csv.rb#L15) are working with a file handle or an IO, so it shouldn't be impossible to refactor it.

You can also use some libraries to detect the file type without using the extension, like:
https://github.com/blackwinter/ruby-filemagic
https://github.com/mimemagicrb/mimemagic

**Comment by alchaplinsky** [comment]
I'm not saying it is impossible to detect mime type for instance. However, it is not trivial task and I don't think it is worth the effort. See my points below:

1. You're right DocX, Pdf, CSV, etc. are accepting IO object. However, those are specific content parsers. They don't try to intelligently guess content type. If you pass PDF to CSV or vice versa parsing will fail.
2. This seems like a narrowish use case when you want to pass IO data that is **already downloaded** to Loader so that it magically detects the type and calls the correct Processor. Not sure if adding `mimemagic` or  any other dependency for such a use case is a good idea.
3. Even if we wanted to add some library to detect mime-type for this use case this is also problematic: 
  - `mimemagic` - requires a copy of the Freedesktop.org shared-mime-info database to be downloaded. But even then it fails to detect correct content types.
  - `marcel` - gem used inside rails to detect mime types. Would return general `application/octet-stream` for IO object containing txt, json or yaml data, which is not really helpful.
 4. Detecting content type is not really Loader's responsibility. It's responsibility to load the data from file or URL. This magic Processor detection is just an additional sugar which works because files have extensions and server response contains `content-type` header, so that we can make a decision which processor to call.

Proposed functionality might be a part of a different module, which then can be used to solve a problem like yours. But as I said it is not a trivial task, and if you can come up with a robust solution for this I'd be glad to incorporate it into the library 🍻
